apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.backend.name }}
spec:
  selector:
    app: {{ .Values.apps.backend.name }}
  type: ClusterIP
  ports:
    - port: {{ .Values.service.backend.externalPort }}
      targetPort: {{ .Values.service.backend.internalPort }}
